//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public byte[] MainPhotoGUID { get; set; }
        public string Description { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> Visits { get; set; }
        public Nullable<int> Likes { get; set; }
    }
}
